# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 33, 32, 510110, tzinfo=utc))),
                ('value', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('priceManos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('CHOSEN', 'C'), ('WAITING', 'W')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_min', models.DateTimeField()),
                ('date_max', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CREATED', 'C'), ('QUOTED', 'Q'), ('FINISHED', 'F')], default='C', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 33, 32, 510110, tzinfo=utc))),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=200)),
                ('jobRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.JobRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'A'), ('INACTIVE', 'I')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 33, 32, 494484, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('VALIDATED', 'V'), ('UNVALIDATED', 'U')], default='U', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiREST.User')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Subcategory'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.User'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.JobRequest'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Worker'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Worker'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.User'),
        ),
    ]
