# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 40, 15, 778816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 40, 15, 778816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 21, 21, 40, 15, 747557, tzinfo=utc)),
        ),
    ]
