# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0003_auto_20170521_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 22, 2, 19, 26, 900930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 22, 2, 19, 26, 904930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 22, 2, 19, 26, 894931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'A'), ('INACTIVE', 'I')], default='A', max_length=10),
        ),
    ]
